name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      # - name: Load cached venv
      #   id: cached-poetry-dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: .venv
      #     key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry update --no-interaction
          poetry install --no-interaction

      - name: Install munet project
        run: poetry install -E ci --no-interaction

      - name: Lint the project
        run: make ci-lint

      - name: Make sure podman image is present
        run: sudo podman pull docker.io/labn/docker-ci-test:20.04

      - name: Expose the environment
        run: |
          uname -a || true
          cat /etc/os-release || true
          cat /proc/meminfo || true
          cat /proc/cpuinfo || true

      - name: Run tests
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          verbose: true
          files: ./coverage.xml
          # fail_ci_if_error: false
