name: Test Publish to PyPI
on:
  pull_request:
    types: [ closed ]

jobs:
  test-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1
      - uses: actions/checkout@v4
      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi "${{ secrets.TEST_PYPI_API_KEY }}"
      - name: publish package (test)
        run: poetry publish --dry-run -vvv --no-interaction --build -r testpypi
